### ISSUE TITLE
Adding gallery to page

### ISSUE THREAD

**Issue by benjamingr** [Gizra/huji-openscholar-hebrew-build#1]
Hey, pretty dumb question.

I'd like to avoid adding a whole theme or messing with it too much. I have a page (namely https://scholars.huji.ac.il/gruenbaum/people) and I want to add an image gallery (rotating image carousel perhaps) to it. 

Normally I'd solve it through CSS but I can't add a `@keyframes` definition to rotate image ala codepen.io/antoniskamamis/pen/hjBrE since `<style>` tags are prohibited. I can't add JS (although no user input) either.

I saw I can add a subtheme but that looks like overkill.  

I'd love to be able to do one of the following:

 - Add a `<style>` tag or a `<link>` tag to a post page - that would let me solve it with css.
 - Embed a widget in a page. This would let me use the existing gallery widget.
 - Be able to include JavaScript in a page (since it is not exposed to end users - I'm not sure why it's prohibited to begin with).

Thanks in advance, let me know if I can help you with additional info.

Cheers,
Benjamin

**Comment by maayan** [comment]
Hi @benjamingr 
We currently do support for HUJI users via mail (working on getting ticketing system). 
Please send us your question via mail to scholars@savion.huji.ac.il and we'll provide instructions.
Thanks,
Ma'ayan

**Comment by benjamingr** [comment]
Hi @maayan I'm asking for a feature from the platform and not for a particular user support ticket. I'm not sure why email is the appropriate channel for this but I can send you an email too if you'd like.
